""" This text file containg test cases for 101-lazy_matrix_mul function"""
>>> lazy_matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul

Try This:
	>>> lazy_matrix_mul("hello", [[1, 2, 3], [2, 4, 5]])
	Traceback (most recent call last):
	ValueError: Scalar operands are not allowed, use '*' instead

	>>> lazy_matrix_mul([[1, 2, 3], [2, 4, 5]], "hello")
        Traceback (most recent call last):
        ValueError: Scalar operands are not allowed, use '*' instead

	>>> lazy_matrix_mul(10, [[1, 2, 3], [2, 4, 5]])
        Traceback (most recent call last):
        ValueError: Scalar operands are not allowed, use '*' instead

	>>> lazy_matrix_mul([[1, 2, 3], [2, 4, 5]], 11)
        Traceback (most recent call last):
        ValueError: Scalar operands are not allowed, use '*' instead

	>>> lazy_matrix_mul([1, 2 ,3], [[1, 2, 3], [2, 4, 5]])
        Traceback (most recent call last):
	ValueError: shapes (3,) and (2,3) not aligned: 3 (dim 0) != 2 (dim 0)

	>>> lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]]) # doctest: +NORMALIZE_WHITESPACE
        array([[ 7, 10],
           [15, 22]])
	
	>>> lazy_matrix_mul([], [[1, 2, 3], [2, 4, 5]])
        Traceback (most recent call last):
	ValueError: shapes (0,) and (2,3) not aligned: 0 (dim 0) != 2 (dim 0)

	>>> lazy_matrix_mul([[]], [[1, 2, 3], [2, 4, 5]])
        Traceback (most recent call last):
	ValueError: shapes (1,0) and (2,3) not aligned: 0 (dim 1) != 2 (dim 0)
	
	>>> lazy_matrix_mul([[1, 2, 3], [2, 4, 5]], [])
        Traceback (most recent call last):
	ValueError: shapes (2,3) and (0,) not aligned: 3 (dim 1) != 0 (dim 0)

        >>> lazy_matrix_mul([[1, 2, 3], [2, 4, 5]], [[]])
        Traceback (most recent call last):
	ValueError: shapes (2,3) and (1,0) not aligned: 3 (dim 1) != 1 (dim 0)
	
	>>> lazy_matrix_mul(["h", 1, 2], [[1, 2, 3], [2, 4, 5]])
        Traceback (most recent call last):
	ValueError: shapes (3,) and (2,3) not aligned: 3 (dim 0) != 2 (dim 0)
        
	>>> lazy_matrix_mul([[12, 'h', 3], [3, 5, 6]], [[1, 2, 3], [2, 4, 5]])
        Traceback (most recent call last):
	ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)
	


	>>> lazy_matrix_mul([[1, 2], [1, 2, 3]], [[1, 2, 3], [2, 4, 5]])
        Traceback (most recent call last):
	ValueError: setting an array element with a sequence.
	
	>>> lazy_matrix_mul([[1, 2, 3], [2, 4, 5]], [[1, 2], [1, 2, 3]])
        Traceback (most recent call last):
	ValueError: setting an array element with a sequence.
	
	>>> lazy_matrix_mul() # doctest: +NORMALIZE_WHITESPACE
        Traceback (most recent call last):
	TypeError: lazy_matrix_mul() missing 2 required positional arguments: 'm_a' and 'm_b'

	>>> lazy_matrix_mul(("h")) # doctest: +NORMALIZE_WHITESPACE
        Traceback (most recent call last):
        TypeError: lazy_matrix_mul() missing 1 required positional argument: 'm_b'

	>>> lazy_matrix_mul(None, None)
        Traceback (most recent call last):
	TypeError: Object arrays are not currently supported

	>>> lazy_matrix_mul([[1, 2], ["12", "b"]], [[10, 9], [1, 7]])
        Traceback (most recent call last):
	TypeError: invalid data type for einsum

	>>> lazy_matrix_mul([[1, 2], [10, 12]], [[10, 9, 1], [1, 7]])
        Traceback (most recent call last):
	ValueError: setting an array element with a sequence.

	>>> lazy_matrix_mul([[1, 2], [10, 12, 5]], [[10, 9, 1], [1, 7, 8]])
        Traceback (most recent call last):
        ValueError: setting an array element with a sequence.

